# Generated by Django 4.1.1 on 2023-01-08 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=255)),
                ('DOB', models.DateField()),
                ('AGE', models.IntegerField()),
                ('GENDER', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Transgender', 'Transgender')], max_length=255)),
                ('PHONE_NUMBER', models.IntegerField()),
                ('MAIL_ID', models.CharField(max_length=255)),
                ('ADDRESS', models.TextField(max_length=1000)),
                ('PURPOSE', models.CharField(choices=[('Enquiry', 'Enquiry'), ('Place Order', 'Place Order'), ('Return', 'Return')], max_length=255)),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Education.course')),
                ('DEPARTMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Education.department')),
            ],
        ),
    ]
