# Generated by Django 4.1.1 on 2023-01-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0003_student_form_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_form',
            name='COURSE',
            field=models.CharField(default='B.Sc', max_length=255, null=True),
        ),
    ]
